name: JSON schema validator
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: development
    paths:
      - 'api/src/config/contextual_search_logic.json'
      - 'api/src/config/contextual_search_logic_schema.json'

jobs:
  json-schema-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install jsonschema
      run: pip install jsonschema
    - name: Schema validation
      id: schema
      run: python api/scripts/json_schema_validator.py > validation.report
    - name: Prepare schema validator comment
      if: failure()
      run: |
        echo "Validation check failed" > comment.md; cat validation.report >> comment.md; cat validation.report >> comment.md
    - name: Prepare success comment
      run: |
        echo "Validation check succesfull" > comment.md; cat validation.report >> comment.md
    - name: Post comment validator comment
      if: always()
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      uses: NejcZdovc/comment-pr@v1.1.1
      with:
        file: "../../comment.md"
